// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/olegshishkin/financier/pkg/adapters/input/rest/server"
)

// Injectors from wire.go:

func Wire() *server.Server {
	logger := provideSourceLogger()
	wrapper := provideWebLogger(logger)
	swaggerHandler := provideSwaggerHandler(wrapper)
	accountStorageStub := provideAccountStorageStub()
	accountService := provideAccountService(accountStorageStub)
	accountHandler := provideAccountHandler(accountService)
	handlerDelegate := provideHandlerDelegate(swaggerHandler, accountHandler)
	middlewares := provideServerMiddlewares(wrapper)
	serverServer := provideServer(wrapper, handlerDelegate, middlewares)
	return serverServer
}
