// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func WireStubs() *gin.Engine {
	accountStorageStub := provideAccountStorageStub()
	accountService := provideAccountService(accountStorageStub)
	accountHandler := provideAccountHandler(accountService)
	engine := provideGinRouter(accountHandler)
	return engine
}
