openapi: "3.0.3"
info:
  version: 0.0.1
  title: Financier API
  description: OpenAPI specification of the Financier service
  contact:
    name: Financier developer
    email: olegshishkin@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080/api/v1
paths:
  /accounts:
    get:
      description: Returns all accounts.
      operationId: getAllAccounts
      parameters: [ ]
      responses:
        '200':
          description: account response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates new account.
      operationId: addAccount
      requestBody:
        description: Account to add.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAccount'
      responses:
        '200':
          description: account response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /accounts/{id}:
    get:
      description: Returns an account by its ID.
      operationId: findAccountByID
      parameters:
        - name: id
          in: path
          description: ID of account to fetch
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Id'
      responses:
        '200':
          description: account response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Account:
      allOf:
        - $ref: '#/components/schemas/Id'
        - $ref: '#/components/schemas/NewAccount'
    Id:
      type: object
      properties:
        id:
          type: string
          minLength: 1
          maxLength: 36
          example: 123
      required:
        - id
      additionalProperties: false
    NewAccount:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          example: wallet
      required:
        - name
      additionalProperties: false
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int8
          minimum: 0
          maximum: 127
          example: 1
        message:
          type: string
          minLength: 1
          maxLength: 4000
          example: Unexpected error
      required:
        - code
        - message
      additionalProperties: false