name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
  pull_request:

env:
  GO_VERSION: 1.19

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build application
        run: make

      - name: Tar files
        if: github.event_name == 'workflow_call'
        run: tar -cvf files.tar .

      - name: Upload artifact
        if: github.event_name == 'workflow_call'
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: files.tar
